# This is a basic workflow to help you get started with Actions

name: Newman Run

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master       
      - name: Run postman tests in a collection with newman action
      - uses: matt-ball/newman-action@master
        with:
          workingDir: data
          collection: collection\FirelyServer.postman_collection
          environment: environment\firely.postman_environment.json
          reporters: cli

      - name: Run a collection folder with a data set
      - uses: matt-ball/newman-action@master
        with:
          folder: Invalid_data_collection
          collection: collection\FirelyServer.postman_collection
          iterationData: data\dataSet.json
          reporters: cli
